version: '2.1'
services:
  ad_mongodb:
    image: mongo
    container_name: ad_mongodb
    restart: always
    ports:
      - ${AD_MONGO_PORT}:27017
    volumes:
      - ./data/mongo/configdb:/data/configdb
      - ./data/mongo/db:/data/db
      - ./data/mongodb/log:/var/log/mongodb  # 挂载日志目录
    command: mongod --auth
    #初始化管理员用户名和密码
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${AD_MONGO_USER}
     MONGO_INITDB_ROOT_PASSWORD: ${AD_MONGO_PWD}
     MONGO_INITDB_DATABASE: ${AD_MONGO_DATABASE}
    tty: true

  ad_elasticsearch:
    image: elasticsearch:7.9.3
    container_name: ad_elasticsearch
    restart: always
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ./data/elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/conf/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./data/elasticsearch/logs:/user/share/elasticsearch/logs:rw
      - ./esplugins:/usr/share/elasticsearch/plugins
    ports:
      - ${AD_ES_PORT}:9200
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.17.1
    ports:
      - "5601:5601"
    container_name: "kibana"
    #restart: always
    depends_on:
      - ad_elasticsearch
    volumes:
      - ./data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  ad_redis:
    image: redis:latest
    container_name: ad_redis
    command: redis-server /etc/redis/redis.conf
    ports:
      - ${AD_REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis/redis.conf:/etc/redis/redis.conf

  ad_server:
    image: jarrettluo/all-docs:${AD_SERVER_IMAGE_TAG}
    container_name: ad_server
    environment:
      - REDIS_HOST=${AD_REDIS_HOST}
      - REDIS_PORT=${AD_REDIS_PORT}
      - REDIS_USER=${AD_REDIS_USER}
      - REDIS_PWD=${AD_REDIS_PWD}
      - MONGO_HOST=${AD_MONGO_HOST}
      - MONGO_PORT=${AD_MONGO_PORT}
      - MONGO_USER=${AD_MONGO_USER}
      - MONGO_PWD=${AD_MONGO_PWD}
      - ES_HOST=${AD_ES_HOST}
      - ES_PORT=${AD_ES_PORT}
      - ES_USER=${AD_ES_USER}
      - ES_PWD=${AD_ES_PWD}
    ports:
      - ${AD_SERVER_PORT}:8082
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8082"]
      interval: 6s
      timeout: 10s
      retries: 20
    depends_on:
      - ad_mongodb
      - ad_redis

  ad_web:
    image: jarrettluo/all-docs-web:${AD_SERVER_IMAGE_TAG}
    container_name: ad_web
    ports:
      - ${AD_WEB_PORT}:80
    depends_on:
      - ad_server